[INSERT_CALL]
dsn=asterisk-connector
writesql=INSERT INTO call_logs (uniqueid, caller_id, destination, dialstatus) VALUES ('${ARG1}', '${ARG2}', '${ARG3}', '${ARG4}')

[UPDATE_CALL]
dsn=asterisk-connector
; ARG1=uniqueid, ARG2=duration, ARG3=disposition, ARG4=dialstatus
writesql=UPDATE call_logs SET duration='${ARG2}', disposition='${ARG3}', call_end=NOW(), dialstatus='${ARG4}' WHERE uniqueid='${ARG1}'