[general]
enabled=yes
bindaddr=0.0.0.0
bindport=8089 ; Can be different from the WSS port, this is for standard HTTP access
tlsenable=yes
tlsbindaddr=0.0.0.0:8088 ; This MUST match the WSS transport port in pjsip.conf
tlscertfile=/etc/asterisk/keys/asterisk.pem
tlsprivatekey=/etc/asterisk/keys/asterisk.key