[general]
enabled = yes
port = 5038
bindaddr = 0.0.0.0
displayconnects = no

[flaskuser]
secret = flasksecret
deny = 0.0.0.0/0.0.0.0
permit = 172.0.0.0/8 ; Restrict to Docker network
read = all
write = all
