[general]
enabled=yes
tlsenable=yes
tlsbindaddr=0.0.0.0:8089
udpbindaddr=0.0.0.0:5060
transport=udp,ws,wss
disallow=all
allow=ulaw,alaw,vp8,h264
nat=force_rport,comedia
videosupport=yes
avpf=yes
encryption=yes
icesupport=yes
dtlsenable=yes
dtlsverify=fingerprint
dtlscertfile=/etc/asterisk/keys/asterisk.crt
dtlsprivatekey=/etc/asterisk/keys/asterisk.key
dtlssetup=actpass

[1000]
type=friend
host=dynamic
secret=password
context=from-internal
callerid="WebRTC Browser" <1000>
transport=ws,wss,udp
disallow=all
allow=ulaw,alaw,vp8,h264
encryption=yes
avpf=yes
icesupport=yes
dtlsenable=yes
dtlsverify=fingerprint
dtlscertfile=/etc/asterisk/keys/asterisk.crt
dtlsprivatekey=/etc/asterisk/keys/asterisk.key
dtlssetup=actpass
nat=force_rport,comedia
directmedia=no
qualify=yes
rtpkeepalive=30
