[general]
format=wav49|wav|ulaw

[default]
1000 => 1234,User One Thousand,user1000@example.com
1001 => 2345,User One Thousand One,user1001@example.com
1002 => 5678,User One Thousand Two,user1002@example.com
1003 => 7890,User One Thousand Three,user1003@example.com
